sonar.projectKey=suprimek0_frontend-project-46
sonar.organization=suprimek0
sonar.projectName=Frontend Project 46
sonar.projectVersion=1.0

# Исходный код
sonar.sources=src
sonar.exclusions=**/*.test.js,**/__tests__/**

# Тесты
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js

# Кодировка
sonar.sourceEncoding=UTF-8

# Отчёты о покрытии
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-results.xml

# Настройки для GitHub Actions
sonar.scm.provider=git
sonar.pullrequest.branch=${GITHUB_HEAD_REF}
sonar.pullrequest.key=${GITHUB_RUN_NUMBER}
sonar.pullrequest.base=${GITHUB_BASE_REF}